trigger:
  branches:
    include:
      - main

pool:
  name: abela-k8-dk  # ✅ Your self-hosted agent name

variables:
  terraformVersion: '1.6.6'
  terraformPath: '$(Agent.TempDirectory)\terraform'  # Safe workspace path

stages:
  - stage: DeployTerraform
    jobs:
      - job: InstallAndRunTerraform
        displayName: 'Install Terraform and Deploy Infra'
        steps:
          
          # ✅ Step 1: Download and extract Terraform
          - powershell: |
              $version = "$(terraformVersion)"
              $dest = "$(terraformPath)"
              Write-Host "Downloading Terraform v$version..."
              Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/$version/terraform_${version}_windows_amd64.zip" -OutFile "terraform.zip"

              if (Test-Path $dest) { Remove-Item -Recurse -Force $dest }
              New-Item -ItemType Directory -Path $dest

              Write-Host "Extracting Terraform..."
              Expand-Archive terraform.zip -DestinationPath $dest -Force
              & "$dest\terraform.exe" -version
            displayName: '✅ Install Terraform'

          # ✅ Step 2: Run Terraform using Azure CLI task
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'k8-dk'  # 👈 Your service connection
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                Write-Host "📁 Changing directory to IAC..."
                cd "$(System.DefaultWorkingDirectory)\IAC"

                Write-Host "🛠️ Running terraform init..."
                terraform init

                Write-Host "🧪 Running terraform plan..."
                terraform plan -out=tfplan

                Write-Host "🚀 Running terraform apply..."
                terraform apply -auto-approve tfplan
            env:
              PATH: $(terraformPath);$(PATH)  # ✅ Add Terraform to PATH
            displayName: '🚀 Terraform Init, Plan, Apply'
