trigger:
  branches:
    include:
      - main

pool:
  name: abela-k8-dk  # Replace with your actual agent pool name

variables:
  terraformVersion: '1.6.6'

stages:
  - stage: DeployTerraform
    jobs:
      - job: RunTerraform
        displayName: 'Install Terraform and Apply Infrastructure'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'k8-dk'  # Replace with your service connection name
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                $ErrorActionPreference = "Stop"

                Write-Host "Downloading Terraform v$(terraformVersion)..."
                $tfUrl = "https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_windows_amd64.zip"
                Invoke-WebRequest -Uri $tfUrl -OutFile "terraform.zip"

                Write-Host "Extracting Terraform..."
                Expand-Archive -Path terraform.zip -DestinationPath $env:AGENT_TEMPDIRECTORY -Force
                $env:PATH += ";$env:AGENT_TEMPDIRECTORY"

                Write-Host "Verifying Terraform install..."
                terraform -version

                Write-Host "Changing directory to IAC..."
                Set-Location IAC

                Write-Host "Running terraform init..."
                terraform init

                Write-Host "Running terraform plan..."
                terraform plan -out=tfplan

                Write-Host "Running terraform apply..."
                terraform apply -auto-approve tfplan
            displayName: 'Install and Run Terraform'
