trigger:
  branches:
    include:
      - main

pool:
  name: abela-k8-dk  # Replace with your self-hosted agent pool name

variables:
  terraformVersion: '1.6.6'

stages:
  - stage: DeployTerraform
    jobs:
      - job: InstallAndRunTerraform
        displayName: 'Install Terraform and Deploy Infra'
        steps:

          # Step 1: Install Terraform
          - powershell: |
              $terraformVersion = "$(terraformVersion)"
              Write-Host "Downloading Terraform $terraformVersion..."
              Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/$terraformVersion/terraform_${terraformVersion}_windows_amd64.zip" -OutFile "terraform.zip"
              Expand-Archive terraform.zip -DestinationPath "$env:USERPROFILE\terraform" -Force
              $env:PATH += ";$env:USERPROFILE\terraform"
              terraform -version
            displayName: 'Install Terraform'
            env:
              PATH: $(PATH);$(USERPROFILE)\terraform

          # Step 2: Terraform Init, Plan, Apply
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'k8-dk'  # Replace with your Azure service connection name
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                Write-Host "Changing directory to IAC..."
                cd "$(System.DefaultWorkingDirectory)\IAC"

                Write-Host "Running terraform init..."
                terraform init

                Write-Host "Running terraform plan..."
                terraform plan -out=tfplan

                Write-Host "Running terraform apply..."
                terraform apply -auto-approve tfplan
            displayName: 'Terraform Init, Plan, Apply'
