trigger:
  branches:
    include:
      - main

# ✅ Use your self-hosted agent instead of Microsoft-hosted Ubuntu
pool:
  name: Default  # Or your agent pool name
  demands:
    - agent.name -equals abela-k8-dk

variables:
  terraformVersion: '1.6.6'

stages:
  - stage: DeployTerraform
    jobs:
      - job: InstallAndRunTerraform
        displayName: 'Install Terraform and Deploy Infra'
        steps:

          # Step 1: Install Terraform manually
          - script: |
              echo "Installing Terraform v$(terraformVersion)..."
              curl -s -o terraform.zip https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_windows_amd64.zip
              tar -xf terraform.zip || unzip terraform.zip
              move terraform.exe C:\Windows\System32\
              terraform -version
            displayName: 'Install Terraform'

          # Step 2: Login to Azure using Service Connection
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'k8-dk'  # 🔁 Use your actual service connection name
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running Terraform..."
                cd IAC
                terraform init
                terraform plan -out=tfplan
                terraform apply -auto-approve tfplan
            displayName: 'Terraform Init, Plan, Apply'
